models:
  - type: coder_same_bug
    engine: nim
    model: meta/llama-3.2-1b-instruct
  - type: coder_rename_variable
    engine: nim
    model: meta/llama-3.2-1b-instruct
  - type: tester_report
    engine: nim
    model: meta/llama-3.2-1b-instruct
  - type: self_check_input
    engine: nim
    model: meta/llama-3.2-1b-instruct
  - type: main
    engine: nim
    model: meta/llama-3.2-1b-instruct

enable_rails_exceptions: true

rails:
  input:
    flows:
      - self check input
